# Spring cloud stream 默认生产者的配置
spring:
  cloud:
    stream:
      bindings:
        output: # binding的key为output
#          binder: # 指定某个binder, 不指定时使用default-binder的配置
          destination: ${spring.application.name}.default
#          group: # queue的后缀,带业务含义; 由各业务系统自身定义
          contentType: application/json
