# Spring cloud stream 默认生产者的Binding属性，针对于RabbitMq的特性
spring:
  cloud:
    stream:
      #属于特定于RabbitMq的Binding,不是通用的,如果涉及到mq的转换则不可用; 同样以key的方式指定配置，默认为default
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: topic # 指定Exchange类型