# Spring cloud stream 默认普通消费者的Binding属性，针对于RabbitMq的特性
spring:
  cloud:
    stream:
      #属于特定于RabbitMq的Binding,不是通用的,如果涉及到mq的转换则不可用; 同样以key的方式指定配置，默认为default
      rabbit:
        bindings:
          input:
            consumer:
              # 手动确认
              acknowledgeMode: MANUAL
              ttl: 1800000 # ms, 默认不做限制, 消息在队列中最大的存活时间; 当消息滞留超过ttl时会被当成消费失败消息, 即会被转发到死信队列或丢弃
              autoBindDlq: true # 是否自动声明死信队列(DLQ)并将其绑定到死信交换机(DLX),默认是false
