# Spring cloud bus 默认约定配置： 生产者和消费者的默认能力
spring:
  cloud:
    stream:
      bindings:
        springCloudBusOutput:
          destination: ${spring.application.name}.default # exchange 或 topic 用生产者的applicationName做前缀
          contentType: application/json
