# Spring cloud bus 默认生产者(springCloudBusOutput)的约定配置
spring:
  cloud:
    stream:
      bindings:
        #以Channel的BeanName为Key所对应的Binding(BindingServiceProperties#bindings)的定义
        springCloudBusOutput:
#          binder: # 指定某个binder, 不指定时使用default-binder的配置
          destination: ${spring.application.name}.default # exchange 或 topic 用生产者的applicationName做前缀
#          group: # queue的后缀,带业务含义; 由各业务系统自身定义
          contentType: application/json
