# Spring cloud stream 默认普通消费者的配置
spring:
  cloud:
    stream:
      bindings:
        input: # binding的key为input
#          binder: rabbitCluster # 指定某个binder, 通常不需要, 由default-binder配置
          destination: ${gm.bustream.default-producer-name}.exchange1
#          group: xxx # queue的后缀,带业务含义; 由各业务系统自身定义
          contentType: application/json
          consumer:
            maxAttempts: 3 # 当消息消费失败时，尝试消费该消息的最大次数（消息消费失败后，发布者会重新投递）。默认3
            backOffInitialInterval: 1000 # 消息消费失败后重试消费消息的初始化间隔时间。默认1s，即第一次重试消费会在1s后进行
            backOffMultiplier: 2 # 相邻两次重试之间的间隔时间的倍数。默认2，即第二次是第一次间隔时间的2倍，第三次是第二次的2倍
            backOffMaxInterval: 10000 # 下一次尝试重试的最大时间间隔，默认为10000ms，即10s
