#RabbitMq特定的Binder(BindingServiceProperties)配置
spring:
  cloud:
    stream:
      binders:
        #以Binder的名称为Key所对应的(BindingServiceProperties#binders->BinderProperties)
        rabbitCluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${spring.rabbitmq.addresses}
                cache:
                  channel:
                    size: 10
                    checkout-timeout: 1s
                  connection:
                    mode: channel
                connection-timeout: 3s
                password: ${spring.rabbitmq.password}
                username: ${spring.rabbitmq.username}
                virtual-host: ${spring.rabbitmq.virtual-host}
