
/* Create Tables */

-- 操作审计日志表
CREATE TABLE OPER_ADT_LOG
(
	-- ID
	ID INT NOT NULL,
	-- 用户登录ID
	LOGIN_ID VARCHAR(64) NOT NULL,
	-- 请求交易URI
	REQUEST_URI VARCHAR(100) NOT NULL,
	-- 请求报文
	REQUEST_BODY VARCHAR(2500),
	-- 操作时间
	OPER_TIME TIMESTAMP NOT NULL,
	-- 版本号
	JPA_VERSION INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PG_KEY_CONTEXT
(
    -- ID
    CONTEXT_ID INT NOT NULL,
    CONTEXT_ID2 INT NOT NULL,
    -- 操作时间
    SETUP_DATE TIMESTAMP NOT NULL,
    -- 版本号
    JPA_VERSION INT NOT NULL,
    PRIMARY KEY (CONTEXT_ID,CONTEXT_ID2)
);



